### ISSUE TITLE
Turning off normalization

### ISSUE THREAD

**Issue by bsphinney** [ftwkoopmans/msdap#32]
Hi ! I want to trun off normalization. 

According to the documentation I do this 

norm_algorithm = c("")

but I get this error downstream

progress: creating PDF report...
error: invalid normalization algorithm provided to normalize_peptide_intensity_column(): must be (and array of) character type and contain at least one non-empty. Provided value: 
Error in append_log(sprintf("invalid normalization algorithm provided to normalize_peptide_intensity_column(): must be (and array of) character type and contain at least one non-empty. Provided value: %s",  : 

any ideas?

Thanks!!

**Comment by ftwkoopmans** [comment]
Coincidentally, I ran into that bug myself a few days ago and this should be fixed in MS-DAP release 1.0.9 that came out earlier today. Please try to update MS-DAP, then rerun your analyses and me know if everything works out.

Run this R snippet in a clean R session (i.e. restart RStudio if it is running) to update

```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
devtools::install_github("ftwkoopmans/msdap", upgrade = "never")
```

**Comment by bsphinney** [comment]
Perfect! Thanks!!

**Comment by bsphinney** [comment]
Look like it worked , but I'm still getting this error

! Undefined control sequence.
l.805 E:\qc
           \ttof\dia\textbackslash50vs200\diann-output\report.tsv 

Error: LaTeX failed to compile report.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See report.log for more info.

I followed all the steps on the issue relating? to this. I think...

https://github.com/ftwkoopmans/msdap/issues/31

**Comment by bsphinney** [comment]
I figured it out

I was using an escape for the windows dir structure \\ 

when I changed it to / 

it worked :)

**Comment by bsphinney** [comment]
I was using "\\" and not "/"

**Comment by bsphinney** [comment]
ugg sorry github is removing my double escape when I type it . You get the idea :)

**Comment by ftwkoopmans** [comment]
ok great that everything's resolved. Good luck with the data analyses
